import CryptoKit
import Foundation

@MainActor
final class LicenseValidator: ObservableObject {
    // MARK: - Constants

    private static let licenseKeyDefaultsKey = "com.2relay.license.key"
    private static let licenseTokenDefaultsKey = "com.2relay.license.token"

    /// Ed25519 public key (raw 32 bytes, base64-encoded).
    /// Generated by scripts/generate_license_keys.sh — matches the private key on the server.
    private static let publicKeyBase64 = "/tExJteIlzEccva/SMTgcVTh0KzBBt2wiuGTObETWQc="

    static let apiBaseURL: String = {
        if let envURL = ProcessInfo.processInfo.environment["TWORELAY_API_URL"] {
            return envURL
        }
        return "https://2relay.2eight.co"
    }()

    // MARK: - Published state

    @Published private(set) var isValidating = false
    @Published private(set) var validationError: String?
    @Published var licenseKey: String = ""
    @Published private(set) var isLicensed: Bool = false

    private let userDefaults: UserDefaults

    // MARK: - Init

    init(userDefaults: UserDefaults = .standard) {
        self.userDefaults = userDefaults
        licenseKey = userDefaults.string(forKey: Self.licenseKeyDefaultsKey) ?? ""

        // A stored token with a valid signature = lifetime license. No expiry check.
        if let token = userDefaults.string(forKey: Self.licenseTokenDefaultsKey) {
            isLicensed = Self.verifySignature(of: token)
        }
    }

    // MARK: - Validate (initial activation from onboarding)

    func validate() async {
        let trimmed = licenseKey.trimmingCharacters(in: .whitespacesAndNewlines)

        guard !trimmed.isEmpty else {
            validationError = "Please enter your license key."
            return
        }

        isValidating = true
        validationError = nil

        do {
            let response = try await callValidationAPI(key: trimmed)

            if response.valid, let token = response.token, Self.verifySignature(of: token) {
                userDefaults.set(trimmed, forKey: Self.licenseKeyDefaultsKey)
                userDefaults.set(token, forKey: Self.licenseTokenDefaultsKey)
                isLicensed = true
                validationError = nil
            } else if !response.valid {
                validationError = "License key not found. Please check and try again."
            } else {
                validationError = "License verification failed. Please try again."
            }
        } catch {
            validationError = "Could not verify license. Check your connection and try again."
        }

        isValidating = false
    }

    // MARK: - Refresh (called on every app launch, best-effort)

    /// Silently checks with the server on launch. If the server says the key
    /// was revoked (chargeback), the license is removed. If offline, the
    /// existing signed token keeps working forever — it's a lifetime purchase.
    func refreshTokenIfNeeded() async {
        let storedKey = userDefaults.string(forKey: Self.licenseKeyDefaultsKey) ?? ""
        guard !storedKey.isEmpty else { return }

        do {
            let response = try await callValidationAPI(key: storedKey)

            if response.valid, let token = response.token, Self.verifySignature(of: token) {
                // Fresh token — store it
                userDefaults.set(token, forKey: Self.licenseTokenDefaultsKey)
                isLicensed = true
            } else if !response.valid {
                // Server explicitly says invalid — key was revoked (chargeback)
                userDefaults.removeObject(forKey: Self.licenseTokenDefaultsKey)
                isLicensed = false
            }
        } catch {
            // Network error — do nothing. Existing token stays valid.
            // This is a lifetime license; offline use is fine.
        }
    }

    // MARK: - Ed25519 signature verification (CryptoKit)

    /// Verifies that the token was signed by our server's private key.
    /// Does NOT check expiry — this is a lifetime license. The signature
    /// alone proves the token came from us and wasn't tampered with.
    private static func verifySignature(of token: String) -> Bool {
        let parts = token.split(separator: ".", maxSplits: 1)
        guard parts.count == 2 else { return false }

        let payloadB64 = String(parts[0])
        let signatureB64 = String(parts[1])

        guard let publicKeyData = Data(base64Encoded: publicKeyBase64),
              publicKeyData.count == 32 else { return false }

        guard let publicKey = try? Curve25519.Signing.PublicKey(rawRepresentation: publicKeyData) else {
            return false
        }

        guard let signatureData = base64urlDecode(signatureB64) else { return false }

        let payloadBytes = Data(payloadB64.utf8)
        guard publicKey.isValidSignature(signatureData, for: payloadBytes) else { return false }

        // Decode payload to check product field
        guard let payloadData = base64urlDecode(payloadB64),
              let payload = try? JSONDecoder().decode(TokenPayload.self, from: payloadData) else {
            return false
        }

        return payload.product == "2relay-macos" && payload.version >= 1
    }

    private struct TokenPayload: Decodable {
        let license_key: String
        let product: String
        let issued_at: Int
        let expires_at: Int
        let version: Int
    }

    // MARK: - API call

    private struct ValidationResponse {
        let valid: Bool
        let token: String?
    }

    private func callValidationAPI(key: String) async throws -> ValidationResponse {
        let url = URL(string: "\(Self.apiBaseURL)/api/validate")!
        var request = URLRequest(url: url)
        request.httpMethod = "POST"
        request.setValue("application/json", forHTTPHeaderField: "Content-Type")
        request.timeoutInterval = 15

        let body = ["license_key": key]
        request.httpBody = try JSONSerialization.data(withJSONObject: body)

        let (data, response) = try await URLSession.shared.data(for: request)

        guard let httpResponse = response as? HTTPURLResponse,
              httpResponse.statusCode == 200 else {
            throw URLError(.badServerResponse)
        }

        guard let json = try JSONSerialization.jsonObject(with: data) as? [String: Any],
              let valid = json["valid"] as? Bool else {
            throw URLError(.cannotParseResponse)
        }

        let token = json["token"] as? String
        return ValidationResponse(valid: valid, token: token)
    }

    // MARK: - Testing support

    /// Bypasses cryptographic verification for unit tests only.
    /// In production the only way to activate is with a server-signed token.
    #if DEBUG
    func forceActivateForTesting() {
        isLicensed = true
    }
    #endif

    // MARK: - Base64url helpers

    private static func base64urlDecode(_ string: String) -> Data? {
        var base64 = string
            .replacingOccurrences(of: "-", with: "+")
            .replacingOccurrences(of: "_", with: "/")

        let remainder = base64.count % 4
        if remainder > 0 {
            base64 += String(repeating: "=", count: 4 - remainder)
        }

        return Data(base64Encoded: base64)
    }
}
